import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/_components/Header";
import ThemeProvider from "@/_components/ThemeProvider";
import Footer from "@/_components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-linear-to-tl dark:from-black dark:via-[#060647] dark:to-black`}
      >
        <ThemeProvider>
        <Header/>
        <div>
        {children}
        </div>
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
