import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/components/themeProvider"
import Header from "@/components/header"
import Footer from "@/components/footer"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        {/* <Header2/> */}
        <Header/>
        <div>
          
          {/* <div className="bg-[repeating-linear-gradient(45deg,_#00000066_0px,_#00000066_1px,_transparent_1px,_transparent_6px)] blur-[2px] dark:blur-[2px] dark:bg-[repeating-linear-gradient(45deg,_#ffffff66_0px,_#ffffff66_1px,_transparent_1px,_transparent_6px)] fixed h-full opacity-50 pointer-events-none right-0 top-0 w-full z-0"></div> */}
          <div className="lighgredient">
            <div className="flex dark:hidden lightgredient2"></div>
            <div className="hidden dark:flex lightgredient3"></div>
             </div>
          {children}

        </div>
        <Footer/>
        </Providers>
      </body>
    </html>
  );
}
